uvbot_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  Rev60_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev60
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Rev62_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev62
    pid: {p: 100.0, i: 0.01, d: 10.0}
